{{- if .Values.imageCredentials.registry}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playwright-synthetic-monitoring.fullname" . }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}